import { StyleSheet } from 'react-native';
import type { ThemeTokens } from '../../../theme';

export function createQuickRemindersScreenStyles(tokens: ThemeTokens) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: tokens.bg },
    listFlex: { flex: 1 },
    scroll: { padding: 16, paddingBottom: 32, flexGrow: 1 },
    headerBlock: { gap: 12, paddingBottom: 4 },
    hint: { fontSize: 14, lineHeight: 20 },
    inputRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    input: {
      flex: 1,
      borderWidth: 1,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 16,
      color: tokens.text,
      borderColor: tokens.border,
      backgroundColor: tokens.surface,
    },
    addBtn: {
      width: 48,
      height: 48,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: tokens.primary,
    },
    empty: { fontSize: 15, textAlign: 'center', marginTop: 24, color: tokens.textFaint },
    row: {
      borderWidth: StyleSheet.hairlineWidth,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      borderColor: tokens.border,
      backgroundColor: tokens.surface,
    },
    rowMain: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      minWidth: 0,
    },
    reorderHit: {
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 4,
      paddingRight: 2,
    },
    toggle: { padding: 2 },
    rowTextPressable: { flex: 1, minWidth: 0 },
    rowText: { fontSize: 16 },
    editModalRoot: { flex: 1, justifyContent: 'center', padding: 24 },
    editOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: tokens.overlay },
    editCard: {
      borderRadius: 16,
      borderWidth: StyleSheet.hairlineWidth,
      padding: 18,
      gap: 14,
      maxWidth: 400,
      width: '100%',
      alignSelf: 'center',
      backgroundColor: tokens.surface,
      borderColor: tokens.border,
    },
    editTitle: { fontSize: 18, fontWeight: '600', color: tokens.text },
    editInput: {
      borderWidth: 1,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 16,
      minHeight: 88,
      textAlignVertical: 'top',
      color: tokens.text,
      borderColor: tokens.border,
      backgroundColor: tokens.bg,
    },
    editActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10 },
    editBtn: { paddingVertical: 10, paddingHorizontal: 18, borderRadius: 12 },
    editBtnSecondary: { backgroundColor: tokens.surfaceAlt },
    editBtnPrimary: { backgroundColor: tokens.primary },
    editBtnText: { color: tokens.text },
    editBtnTextPrimary: { color: tokens.primaryText },
  });
}
